### ISSUE TITLE
ERROR:  CDB(_CDB_Rewrite_Table:XX000:Input geometry has unknown (0) SRID)

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb-postgresql#139] opened 2015-09-08 08:22 UTC
This seems to happen with a big file (128K rows) latitude/longitude columns + a "non valid row at the end", but it doesn't happen with a small file (20 rows) with the same invalid row at the end.

Please, ask me the file to reproduce the issue as the one I got contains confidential data. (perico.csv)

````
2015-09-08 08:03:46 UTC: Fetching datasource public_url metadata for item id perico.csv?
2015-09-08 08:03:47 UTC: File will be downloaded from xxx
2015-09-08 08:03:48 UTC: Before importer run
2015-09-08 08:03:49 UTC: Starting import for x/perico.csv
2015-09-08 08:03:49 UTC: Unpacking x/perico.csv
2015-09-08 08:03:49 UTC: Filename: x/perico.csv Size (bytes): 11547419
true: Importing data fromx/perico.csv
true: File-based import load
true: Detected encoding ISO-8859-1
true: Using database connection with {:adapter=>"postgres", :encoding=>"unicode", :host=>"x", :database=>"x", :username=>"postgres", :port=>5432, :connect_timeout=>2.5, :user=>"x"}
false: ogr2ogr call:            OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=ISO-8859-1  /usr/bin/ogr2ogr2 -f PostgreSQL  -oo AUTODETECT_TYPE=YES -oo QUOTED_FIELDS_AS_STRING=NO -oo X_POSSIBLE_NAMES=longitude,lon,lng,longitudedecimal,longitud,long,decimallongitude,decimallong,point_longitude -oo Y_POSSIBLE_NAMES=latitude,lat,latitudedecimal,latitud,lati,decimallatitude,decimallat,point_latitude PG:"host=10.0.128.17 port=5432 user=x dbname=x password=x"  -lco DIM=2 -lco PRECISION=NO x/perico.csv  -nln x -nlt PROMOTE_TO_MULTI  
true: ogr2ogr output:          
true: ogr2ogr exit code:       0
true: Georeferencing...
true: Disabling autovacuum for "cdb_importer"."x"
true: Creating the_geom from wkb_geometry column
true: replace empty strings by nulls?
true: no string column found, nothing replaced
true: geometrifying
true: casting wkb_geometry to geometry
true: Converting to 2D point
true: Running batched query by id in "cdb_importer"."x": 
                UPDATE "cdb_importer"."x"
                SET wkb_geometry = public.ST_Force_2D(wkb_geometry)
              
true: Using as id 'cartodb_processed_2011713448990830642'
true: Finished batched query by 'cartodb_processed_2011713448990830642' in "cdb_importer"."x": query
true: geometrified
true: Renaming column wkb_geometry TO the_geom
true: found MULTIPOING geometry
true: Converting detected multipoint to point
true: Running batched query by id in "cdb_importer"."x": 
                UPDATE "cdb_importer"."x"
                SET the_geom = ST_GeometryN(the_geom, 1)
              
true: Using as id 'cartodb_processed_2011713448990830642'
true: Finished batched query by 'cartodb_processed_2011713448990830642' in "cdb_importer"."x": query
true: Enabling autovacuum for "cdb_importer".x"
true: Georeferenced
true: Finished importing data from x/perico.csv
2015-09-08 08:04:49 UTC: Proceeding to register
2015-09-08 08:04:49 UTC: Before renaming fromx to perico
2015-09-08 08:04:49 UTC: Before moving schema 'perico' from cdb_importer to iriberri
2015-09-08 08:04:49 UTC: Before persisting metadata 'perico' data_import_id: 0a99b91e-a3e5-49b0-a1be-7619f3411acd
2015-09-08 08:04:56 UTC: Exception: PG::Error: ERROR:  CDB(_CDB_Rewrite_Table:XX000:Input geometry has unknown (0) SRID): CREATE TABLE iriberri.perico_bd036b2ff66a47811eff9b1a90c505dd AS SELECT cartodb_id, ST_Transform(invalid_the_geom,4326)::Geometry(Geometry,4326) AS the_geom, c
2015-09-08 08:04:56 UTC: ["/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in `check_database_errors'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'", 
````

**Comment by rafatower** [comment] 2015-09-10 17:48
Basically we end up with a table with geometries but no SRID (WKT/WKB) right before cartodbfy'ing and it is crashing when trying to convert them to the standard column the_geom.

We've already seen that problem and tried to fix it. I think we should just force the SRID and fail gracefully if there's any further  issue. The funny name `invalid_the_geom` probably comes from ogr2ogr

**Comment by iriberri** [comment] 2015-09-11 08:49
Yep, `invalid_the_geom` is a super typical column that appears when you use an invalid WKT/WKB (like when you miss a character or something like that).

**Comment by rafatower** [comment] 2015-09-11 09:21
ogr2ogr2 produces the following tables from the original file:
```
# \d cdb_importer.importer_09fb2134586611e5b3b10242ac110051
                                              Table "cdb_importer.importer_09fb2134586611e5b3b10242ac110051"
       Column       |           Type           |                                                Modifiers                                                 
--------------------+--------------------------+----------------------------------------------------------------------------------------------------------
 ogc_fid            | integer                  | not null default nextval('cdb_importer.importer_09fb2134586611e5b3b10242ac110051_ogc_fid_seq'::regclass)
 client_uuid        | character varying        | 
 latitude           | double precision         | 
 longitude          | double precision         | 
 location_timestamp | timestamp with time zone | 
 wkb_geometry       | geometry(MultiPoint)     | 
Indexes:
    "importer_09fb2134586611e5b3b10242ac110051_pkey" PRIMARY KEY, btree (ogc_fid)
    "importer_09fb2134586611e5b3b10242ac110051_wkb_geometry_geom_idx" gist (wkb_geometry)
```

so the naming to `invalid_the_geom` should happen later on, and before the cartodbfy.

**Comment by rafatower** [comment] 2015-09-11 09:27
but the srid is set to 0:
```
# select count(1) from cdb_importer.importer_09fb2134586611e5b3b10242ac110051 where st_srid(wkb_geometry) = 0;
 count  
--------
 128038
(1 row)
```

This is the call to ogr2ogr2:
```
OSM_USE_CUSTOM_INDEXING=NO PG_USE_COPY=YES PGCLIENTENCODING=ISO-8859-1  /usr/bin/ogr2ogr2 -f PostgreSQL  -oo AUTODETECT_TYPE=YES -oo QUOTED_FIELDS_AS_STRING=NO -oo X_POSSIBLE_NAMES=longitude,lon,lng,longitudedecimal,longitud,long,decimallongitude,decimallong,point_longitude -oo Y_POSSIBLE_NAMES=latitude,lat,latitudedecimal,latitud,lati,decimallatitude,decimallat,point_latitude PG:"host=development.localhost.lan port=5432 user=development_cartodb_user_fe3b850a-01c0-48f9-8a26-a82f09e9b53f dbname=cartodb_dev_user_fe3b850a-01c0-48f9-8a26-a82f09e9b53f_db password=7482e09bf8947f9729698b1affbcb8931e88774edevelopment_cartodb_user_fe3b850a-01c0-48f9-8a26-a82f09e9b53f"  -lco DIM=2 -lco PRECISION=NO /tmp/imports/20150911-13039-1rrlnks/perico.csv  -nln cdb_importer.importer_09fb2134586611e5b3b10242ac110051 -nlt PROMOTE_TO_MULTI
```
so I'm thinking that probably a better solution, since there's no geometry as such in the original csv but lat and long columns, is to instruct ogr to generate a the_geom with SRID...

**Comment by rafatower** [comment] 2015-09-11 09:34
With the `-t_srs EPSG:4326` option:
```
Can't transform coordinates, source layer has no
coordinate system.  Use -s_srs to set one.
ERROR 1: Terminating translation prematurely after failed
translation of layer perico (use -skipfailures to skip errors)
```
but that's a problem because though I think it is legitimate to always force the target srs it is NOT forcing the source srs in all cases.

**Comment by rafatower** [comment] 2015-09-11 10:13
Closing this for the moment. The root cause is finally not here but in rails app repo. I introduced this issue when adding the new feature of lat/long detection with ogr2ogr and the thing is the root cause is in gdal2.1 itself. I think I found a plausible workaround for it. Stay tuned.

**Closed by rafatower** 2015-09-11 10:13 UTC
Labels: Backlog, bug, cartodbfy

**Comment by iriberri** [comment] 2015-09-11 10:41
Thanks for the updates Rafa!
